// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FASTBuildUtility
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFASTBuildUtilityPackageString = "45e8d138-0f61-44f8-b29a-e604e11e91cd";
        public static Guid guidFASTBuildUtilityPackage = new Guid(guidFASTBuildUtilityPackageString);

        public const string guidFASTBuildUtilityPackageCmdSetString = "d3d22de7-8b47-49ed-b994-0c1debd5949d";
        public static Guid guidFASTBuildUtilityPackageCmdSet = new Guid(guidFASTBuildUtilityPackageCmdSetString);

        public const string guidImagesString = "4cf6cfeb-6dce-4cc0-9ef7-abc892de3562";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CompileSingleFileId = 0x0100;
        public const int cmdidBuildDebugProject = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}